### ISSUE TITLE
NOT SUPPORTED ON BACKBOX WHY?

### ISSUE THREAD

**Issue by rootmzizi** [s0md3v/Striker#54]
Am getting this error why?

root@backbox:/home/lau/Documents/Tools/Striker# python striker.py
Traceback (most recent call last):
  File "striker.py", line 10, in <module>
    from plugins.DNSDumpsterAPI import DNSDumpsterAPI
  File "/home/lau/Documents/Tools/Striker/plugins/DNSDumpsterAPI.py", line 12, in <module>
    from bs4 import BeautifulSoup
  File "/usr/lib/python2.7/dist-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
 File "/usr/lib/python2.7/dist-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/lib/python2.7/dist-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'
root@backbox:/home/lau/Documents/Tools/Striker#

**Comment by s0md3v** [comment]
This project is being re-written. You are trying to run an older version which is no longer being maintained :)

**Comment by rootmzizi** [comment]
I see its under development
