### ISSUE TITLE
Error Traceback

### ISSUE THREAD

**Issue by dzhenway** [s0md3v/Striker#58]
C:\Python3\Striker-master>striker.py evil.com

.
  ` .        .             .        . `
      ` .     .  Striker  .     . `
          ` .` .         . `. `
              ` . ` . ` . `
                  ` . `

[^] Running component level check
[^] Starting engine
Traceback (most recent call last):
  File "C:\Python3\Striker-master\striker.py", line 28, in <module>
    from core.photon import photon
  File "C:\Python3\Striker-master\core\photon.py", line 11, in <module>
    from modules.wappalyzer import wappalyzer
  File "C:\Python3\Striker-master\modules\wappalyzer.py", line 5, in <module>
    signatures = var('tech_signatures')
  File "C:\Python3\Striker-master\core\utils.py", line 27, in var
    return core.config.globalVars[name]
KeyError: 'tech_signatures'

**Comment by mr7Zx** [comment]
Yea me too when using python2 after i use python3 that error

**Comment by Lovra03** [comment]
Is there anything you can do to fix that

**Comment by TaintedSights** [comment]
I'm getting the same error, any help on this?

**Comment by Lovra03** [comment]
Hey man, I haven't been on termux for more then a month but I'm not sure
that the problem is fixed, I think that the new update screwed everything.

Dana subota, 20. srpnja 2019. TaintedSights <notifications@github.com> piše:

**Comment by PentesB** [comment]
Same issue .Did you you guys resolve it?

**Comment by sonawanesarvesh** [comment]
same for me
