### ISSUE TITLE
File "striker.py", line 37, in <module> Someone Help ?

### ISSUE THREAD

**Issue by jianchen21** [s0md3v/Striker#65]
.                   
  ` .        .             .        . `
      ` .     .  Striker  .     . `
          ` .` .         . `. `
              ` . ` . ` . `
                  ` . `

[^] Running component level check
[^] Starting engine
[^] Turning on radar
Traceback (most recent call last):
  File "striker.py", line 37, in <module>
    raw_subdomains = list(set(findsubdomains(sys.argv[1]) + security_trails(sys.argv[1])))
IndexError: list index out of range

**Comment by s0md3v** [comment]
Usage: `python3 striker.py example.com`
You are probably missing the domain name.

**Comment by Jhonny404** [comment]
.                   
  ` .        .             .        . `
      ` .     .  Striker  .     . `
          ` .` .         . `. `
              ` . ` . ` . `
                  ` . `

[^] Running component level check
[^] Starting engine
[^] Turning on radar
[!] 1 targets were caught on radar.
Traceback (most recent call last):
  File "striker.py", line 58, in <module>
    open_ports = portscanner([(ip, port) for port in var('ports')])
  File "/root/Tools/Striker/modules/portscanner.py", line 16, in portscanner
    for i in concurrent.futures.as_completed(futures):
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 217, in as_completed
    fs = set(fs)
  File "/root/Tools/Striker/modules/portscanner.py", line 15, in <genexpr>
    futures = (threadpool.submit(scan, target, result) for target in targets)
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 160, in submit
    self._adjust_thread_count()
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 181, in _adjust_thread_count
    t.start()
  File "/usr/lib/python3.7/threading.py", line 847, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

**Comment by s0md3v** [comment]
@Jhonny404 can you please share the output of following command?
`ulimit -u`

**Comment by CyberSeaLOps** [comment]
Running component level check
[^] Starting engine
[^] Turning on radar
[!] 3 targets were caught on radar.
Traceback (most recent call last):
  File "striker.py", line 58, in <module>
    open_ports = portscanner([(ip, port) for port in var('ports')])
  File "/root/Lab/Striker/modules/portscanner.py", line 16, in portscanner
    for i in concurrent.futures.as_completed(futures):
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 217, in as_completed
    fs = set(fs)
  File "/root/Lab/Striker/modules/portscanner.py", line 15, in <genexpr>
    futures = (threadpool.submit(scan, target, result) for target in targets)
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 172, in submit
    self._adjust_thread_count()
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 193, in _adjust_thread_count
    t.start()
  File "/usr/lib/python3.7/threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

**Comment by CyberSeaLOps** [comment]
ulimit -u says 15054
