### ISSUE TITLE
Traceback Exceptions

### ISSUE THREAD

**Issue by 5trelets** [s0md3v/Striker#66]
```
[^] Deploying Zoom for subdomain takeovers
[^] Deploying Photon for component assessment
[^] Deploying Alpha for software fingerprinting
[^] Deploying Zetanize for identifying entry points
[!] ETA: 100 seconds
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 841, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a7c7232e8>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='whatcms.org', port=443): Max retries exceeded with url: /?gpreq=json&jsoncallback=jQuery1124008091494457806547_1554361369057&s=static-assets.glossier.com&na=&nb=1cg805dlm7d7e5eickf67rzxrn12mju6bnch3a99hrt88v7n8rhf0lovwr8d0zm1&verified=&_=1554361369059 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a7c7232e8>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "striker.py", line 101, in <module>
    dataset[subdomain]['cms'] = whatcms(subdomain)
  File "/root/Tools/Striker/modules/whatcms.py", line 6, in whatcms
    response = requester('https://whatcms.org/?gpreq=json&jsoncallback=jQuery1124008091494457806547_1554361369057&s=%s&na=&nb=1cg805dlm7d7e5eickf67rzxrn12mju6bnch3a99hrt88v7n8rhf0lovwr8d0zm1&verified=&_=1554361369059' % domain).text
  File "/root/Tools/Striker/core/requester.py", line 22, in requester
    url, params=data, headers=headers, verify=False)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='whatcms.org', port=443): Max retries exceeded with url: /?gpreq=json&jsoncallback=jQuery1124008091494457806547_1554361369057&s=static-assets.glossier.com&na=&nb=1cg805dlm7d7e5eickf67rzxrn12mju6bnch3a99hrt88v7n8rhf0lovwr8d0zm1&verified=&_=1554361369059 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a7c7232e8>: Failed to establish a new connection: [Errno -2] Name or service not known'))
root@kali:~/Tools/Striker# 

```

**Comment by s0md3v** [comment]
Not Striker's fault, it was caused by a network issue. I will reopen this issue and investigate it if it reproduces.

**Comment by zbejas** [comment]
> Not Striker's fault, it was caused by a network issue. I will reopen this issue and investigate it if it reproduces.

Hello. I have the same issue. How can I remedy this?
