### ISSUE TITLE
I have installed striker with all the depandencies but i keep getting this issue

### ISSUE THREAD

**Issue by fachatti-amine** [s0md3v/Striker#86]
command executed: python3 striker.py                     

.                   
  ` .        .             .        . `
      ` .     .  Striker  .     . `
          ` .` .         . `. `
              ` . ` . ` . `
                  ` . `

[^] Running component level check
[^] Starting engine
[^] Turning on radar
Traceback (most recent call last):
  File "striker.py", line 42, in <module>
    source_1 = findsubdomains(sys.argv[1])
IndexError: list index out of range
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_opt_Striker_striker.py.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "striker.py", line 42, in <module>
    source_1 = findsubdomains(sys.argv[1])
IndexError: list index out of range

**Comment by jackson-jackson** [comment]
You're missing the domain. $ python3 striker.py example.com
